language: python
sudo: false

# Currently (1/8/2019) python3.7 requires xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      after_success:
        - codecov

before_install:
  - uname -a

install:
  - pip install .[docs,tests] codecov

before_script:
  - python -V

script:
  - cd /tmp # Move to an unrelated dir
  - pytest --pyargs --cov=basis_set_exchange basis_set_exchange
  - bse -V # Quick test of the cli

notifications:
  email:
    on_success: change
    on_failure: always
